pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mern-backend'
        CONTAINER_NAME = 'backend-app'
        PORT = '5000'
    }

    stages {
        stage('Checkout') {
           steps {

                git branch: 'main', 



                    url:'https://github.com/Siva290395/mern-devops-project.git' 
                    credentialsId: 'github-credentials'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || echo "No tests configured"'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:latest")
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                script {
                    sh '''
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                    '''
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}:latest").run(
                        "-p ${PORT}:5000 --name ${CONTAINER_NAME} -d"
                    )
                }
            }
        }

        stage('Health Check') {
            steps {
                sh '''
                    sleep 5
                    curl -f http://localhost:${PORT}/health || exit 1
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
